---
- name: Update and upgrade apt packages
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 86400 #One day

#- name: install lets Encrypt Repository
#  command: |
#    curl -o- https://raw.githubusercontent.com/vinyll/certbot-install/master/install.sh | bash

- name: obtaining SSL Cert
  command: |
    certbot --non-interactive --agree-tos --nginx -m sockethefourth@gmail.com -d depressive.life -d www.depressive.life